### ISSUE TITLE
End of example marker needed

### ISSUE THREAD

**Issue by twjudson** [rbeezer/mathbook#351] opened 2016-07-31 08:27 UTC
The end of a proof is currently marked by a square or is contained in a knowl.  However, there is no end of example marker.  It is very difficult to tell where an example ends.

**Comment by rbeezer** [comment] 2016-07-31 21:05
This might be a duplicate?  Jason Underdown post?  Could you check?  (Or else it 
is on the mailing list?)

**Comment by rbeezer** [comment] 2016-08-01 18:53
Duplicate of #320

**Closed by rbeezer** 2016-08-01 18:53 UTC
Labels: duplicate
