### ISSUE TITLE
percent in math mode doesn't work right

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#43] opened 2015-02-04 18:33 UTC
`<m>0\leq x <percent /> m &lt;m</m>`

If I leave it as `%`, it works fine in html but not latex.  If I leave it this way, it doesn't show up in HTML.  Exactly the thing that `<percent />` was supposed to avoid... sigh.  It's my fault for putting non-math in there, I know, but anyway thought it was worth reporting.  I have a feeling some other such things will also not render properly in math mode.  My workaround was to get the `%` out of the math and put it in a code tag for now.

**Comment by kcrisman** [comment] 2015-02-04 18:36
It also doesn't appear to work in a Sage block:
```
<input>[ x <percent /> 6 for x in [1, 7, 13, 19, 25, -5, -11, 6001, -17]]</input>
```
I tried using `%` there because it works in html, but apparently messes up the tex (unsurprisingly).

**Comment by rbeezer** [comment] 2015-02-04 18:56
Right, in a Sage block you only need to escape the ampersand and the less-than, using XML syntax like `&amp;`.

Anything inside `<m>` or its cousins strictly follows LaTeX syntax, so you need to do whatever you would do in "regular" LaTeX, in this case use `\%` (which I have tested).

Note you can use `\lt` in your example rather than escaping the less-than character - MathJax predefines it, as does MBX LaTeX preamble.

Everything is behaving as expected, so I am going to close this.

**Closed by rbeezer** 2015-02-04 18:56 UTC

**Comment by kcrisman** [comment] 2015-02-04 19:31
> Anything inside <m> or its cousins strictly follows LaTeX syntax, so you need to do whatever you would do in "regular" LaTeX, in this case use \% (which I have tested).

Okay, that makes sense.

So... is it a bug that `<percent />` *doesn't* work, though?  Shouldn't it do the right thing anyway?  (Hence wondering why this is closed.)

**Comment by rbeezer** [comment] 2015-02-04 23:17
Definitely not a bug.  Inside `<m>` and its ilk, absolutely no processing is requested, so I think that `<percent />` will just be ignored like it didn't exist.  Content inside "math" delimiters is totally LaTeX (well, the subset that MathJax supports, really).  Only.  End of story.  If you want something more, then maybe you really are not in math land anyway.  So no plans to support any XML elements inside math.

So closed because everything here is behaving exactly as designed and expected.

**Comment by kcrisman** [comment] 2015-02-05 02:17
Got it.  Maybe you can add that to the sample article :wink:

**Comment by rbeezer** [comment] 2015-02-05 18:32
I added this to #33 (rolling documentation patch).
