### ISSUE TITLE
pdftex warning

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1043] opened 2019-04-17 12:23 UTC
Like this:
```

[360]pdfTeX warning (ext4): destination with the same identifier (name{cthm.1})

 has been already used, duplicate ignored
```

**Comment by alexjbest** [comment] 2019-04-19 19:56
I found the same issue in a few tex.stackexchange threads https://tex.stackexchange.com/questions/25047/how-do-i-get-rid-of-particular-pdftex-warning-message  https://tex.stackexchange.com/questions/233039/disabling-destination-with-the-same-identifier-with-package-silence .

The fix there is to load the packages in a different order, specifically place hyperref above amsthm.

However I found for our source that while this works, it isn't the root cause.
Specifically the lines
`\newtheorem{cthm}{BadTheoremStringName}[section]`
and 
`\usepackage[hyperfootnotes=false]{hyperref}`
are what matters, with hyperref first producing no warnings, and hyperref second producing a lot.

I didn't test out other reorderings of all the other lines (i.e. I left all the hypersetup lines where they are), and I cannot say what other side effects this has (other than that I didn't see any so far). However "The hyperref documentation says: "Make sure it comes last of your loaded packages""  https://tex.stackexchange.com/questions/1863/which-packages-should-be-loaded-after-hyperref-instead-of-before

**Comment by rbeezer** [comment] 2019-04-22 00:14
Thanks for the sleuthing, Alex!  I mean to remove any dependence on `\newtheorem` in which case this may just go away.  This will be part of moving all the "environment" counters over to `tcolorbox`.

**Comment by rbeezer** [comment] 2021-02-28 20:44
More info on this at sporadic thread:

https://groups.google.com/g/pretext-support/c/kBJR8R-8snQ/m/7prcHie1AQAJ

**Comment by rbeezer** [comment] 2021-02-28 20:47
Relevant counters are under the control of  tcolorbox  and placing hyperref before the tcolorboxes get built seems to be the solution.

Testing with a minimal example suggests the links actually work just fine, even with the warnings.

At  a6288401809b1308e95f8b69259587a55414993a

**Closed by rbeezer** 2021-02-28 20:47 UTC
Labels: bug, code cleanup

**Comment by rbeezer** [comment] 2021-02-28 20:51
Meant to record a workaround if a similar problem arises:

https://tex.stackexchange.com/questions/485251/tcolorbox-potential-bug-with-duplicate-label-for-hyperref-link

**Comment by rbeezer** [comment] 2021-02-28 21:03
And a query upstream:

https://github.com/T-F-S/tcolorbox/issues/135
