### ISSUE TITLE
Implementation of seealso in index could be improved

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#481] opened 2016-12-24 04:23 UTC
Love having seealso tag.  But ... when you use it, it behaves exactly as the see tag.  I tested this by making two index tags for a given item, one with a seealso, one without; both show up in the index but only the one without shows up as a link/page number.

**Comment by rbeezer** [comment] 2016-12-24 18:22
"see" and "seealso" are basically cross-references within the index, rather than to content.  They do not behave exactly the same, one outputs "see" and the other outputs "see also".  If you want a link to content then you have another cross-reference, which you can make as you suggest in your test.

In LaTeX/PDF/print you just get words as the pointer, and there is not even any checking that the words are a real target.  The situation for HTML is (a) more complicated, (b) best saved for after an upcoming xref refactor, (c) going to be a job to duplicate in LaTeX (live references), (d) already suggested on #460.

Please make *positive* suggestions on #460 for enhancements.  You might wish to adopt the xml:id/xref mechanism suggested there for current work, with the usual caveats about getting out front of development.  I'm closing this as a duplicate.

**Comment by kcrisman** [comment] 2016-12-24 18:56
I would like you to reopen this.  You didn't read it properly.  Let me give you the full logic.

- A normal index item should have a link or page number to the spot it appears.
- A see index item should not have this (at least, not ordinarily), since you are supposed to "see" that other reference.  Maybe one could at #460, as you say, but that is not what this is about.
- A see ALSO index item should have you see that ALSO.  That means it should have a reference (link in html, page nr in pdf) AND have the words that say to see also.  

E.g. "Beezer's Theorem, 196.  See also Beezer's Lemma."  As opposed to "Beezer's Theorem; see also Beezer's Lemma", which is more or less current MBX behavior.

The Chicago Manual backs me up, if you care :) See 18.19.  (Also, apparently there is "see under" and "see also under" for subheadings, but I definitely won't open that.)

**Comment by kcrisman** [comment] 2017-01-10 21:56
Ping @rbeezer - please reopen this or confirm that CMoS is no longer relevant 😈

**Comment by rbeezer** [comment] 2017-01-11 03:31
I put this one in a virtual drawer for a while, so I would settle down before replying.

The index is a bunch of cross-references.  "see" and "see also" are cross-references into the index rather than into the content.  The current implementation creates one cross-reference per "index" entry.  So it takes two "index" with matching headings.  The resulting look will match style guides - that part of the discussion is irrelevant.

The implementation is not improper, but as part of its continual improvement, some economy for authors could be achieved by making two cross-references from one "index" in this scenario.  It is not a bug, so not at the top of my list.  But could result in backward incompatiblity.

Rob

**Comment by kcrisman** [comment] 2017-01-11 03:34
I still don't understand why the style guide is not relevant or why the implementation is not improper, but we can talk about it the next time I see you in person - it's not crucial, obviously.

**Comment by rbeezer** [comment] 2019-03-03 23:44
OK, I understand this one now.  Sorry for the attitude earlier.  Lots of new (tighter) code for the index about to be released and then this will be fixed.

In the beginning, most of my style and formatting decisions were guided by LaTeX output.  I can see now that there is a lot to find fault with when it coes to the LaTeX index.

**Comment by rbeezer** [comment] 2019-04-05 03:45
I hope this is now correct.  Work at 847837dc9c037766ad202a7d3890ada4acdfd0b0 and several preceding commits.

**Closed by rbeezer** 2019-04-05 03:45 UTC
Labels: z-index
